package main

import (
	"runtime"
	"unsafe"
)

func run(deltas []int32, iters int) uint64 {
	if len(deltas) == 0 {
		return 0
	}
	return deltaSum(deltas, iters)
}

//go:noescape
func deltaSumAsm64AVX2(deltas unsafe.Pointer, n int, iters int) uint64

//go:noescape
func deltaSumAsm64AVX512(deltas unsafe.Pointer, n int, iters int) uint64

func deltaSum(deltas []int32, iters int) uint64 {
	n := len(deltas)
	if n == 0 {
		return 0
	}

	// Quick runtime dispatch
	if cpuHasAVX512() {
		return deltaSumAsm64AVX512(unsafe.Pointer(&deltas[0]), n, iters)
	}
	if cpuHasAVX2() {
		return deltaSumAsm64AVX2(unsafe.Pointer(&deltas[0]), n, iters)
	}
	return deltaSumScalar(deltas, iters)
}

func deltaSumScalar(deltas []int32, iters int) uint64 {
	const magic = 0x9E3779B1
	var total uint64
	for iter := 0; iter < iters; iter++ {
		var current int64
		total = 0
		for _, d := range deltas {
			current += int64(d)
			total += uint64(current + magic)
		}
	}
	return total
}

// --- minimal CPUID helpers --------------------------------------------------

var (
	hasAVX2   bool
	hasAVX512 bool
)

func cpuHasAVX2() bool   { return hasAVX2 }
func cpuHasAVX512() bool { return hasAVX512 }

func init() {
	detect()
}

func detect() {
	eax, ebx, ecx, edx := cpuid(1, 0)
	hasAVX2 = (ecx & (1 << 28)) != 0 // OSXSAVE
	if hasAVX2 {
		eax, _, ecx, _ = cpuid(7, 0)
		hasAVX2 = (ebx & (1 << 5)) != 0 // AVX2
		hasAVX512 = (ebx & (1 << 16)) != 0 // AVX-512F
	}
	_ = eax // silence unused
	_ = edx // silence unused
}

func cpuid(ax, cx uint32) (uint32, uint32, uint32, uint32) {
	eax, ebx, ecx, edx := ax, uint32(0), cx, uint32(0)
	// Hand-written asm avoids importing x/sys/cpu and keeps binary tiny.
	asmCpuid(&eax, &ebx, &ecx, &edx)
	return eax, ebx, ecx, edx
}

//go:noescape
func asmCpuid(eax, ebx, ecx, edx *uint32)

// ---------------------------------------------------------------------------
// Assembly implementations live in delta_amd64.s (generated by us)
// They are omitted here for brevity; they simply implement the inner loop
// described in the summary using AVX2 or AVX-512 intrinsics and return the sum.